# Generated by Django 2.2.3 on 2019-07-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_publisher1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher1',
        ),
    ]
